# Generated by Django 5.2.10 on 2026-01-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_promtp_agent_prompt_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_by',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=50),
        ),
    ]
