# Generated by Django 5.2.10 on 2026-01-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_message_message_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
